### ISSUE TITLE
ansible-service-broker start fails on accessing docker hub

### ISSUE THREAD

**Issue by matihost** [openshift/ansible-service-broker#584]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**

> # Bug:

**What happened**:

I going through : 

https://github.com/openshift/ansible-service-broker#deploy-an-openshift-origin-cluster-with-the-ansible-service-broker

All commands finished successfully but ASB didn't start:

```
[mati@matihost tmp]$ oc logs asb-1-deploy
--> Scaling asb-1 to 1
[mati@matihost tmp]$ oc logs asb-1-phjq8
Using config file mounted to /etc/ansible-service-broker/config.yaml
============================================================
==           Starting Ansible Service Broker...           ==
============================================================
[2017-12-08T14:53:39.11Z] [NOTICE] Initializing clients...
[2017-12-08T14:53:39.112Z] [DEBUG] Trying to connect to etcd
[2017-12-08T14:53:39.113Z] [INFO] == ETCD CX ==
[2017-12-08T14:53:39.113Z] [INFO] EtcdHost: asb-etcd.ansible-service-broker.svc
[2017-12-08T14:53:39.113Z] [INFO] EtcdPort: 2379
[2017-12-08T14:53:39.113Z] [INFO] Endpoints: [https://asb-etcd.ansible-service-broker.svc:2379]
[2017-12-08T14:53:39.144Z] [INFO] Etcd Version [Server: 3.2.11, Cluster: 3.2.0]
[2017-12-08T14:53:39.144Z] [DEBUG] Connecting to Cluster
[2017-12-08T14:53:39.148Z] [DEBUG] Connecting Dao
[2017-12-08T14:53:39.193Z] [INFO] Kubernetes version: v1.8.1+0d5291c
[2017-12-08T14:53:39.193Z] [DEBUG] Connecting Registry
[2017-12-08T14:53:39.193Z] [INFO] == REGISTRY CX == 
[2017-12-08T14:53:39.193Z] [INFO] Name: dh
[2017-12-08T14:53:39.193Z] [INFO] Type: dockerhub
[2017-12-08T14:53:39.193Z] [INFO] Url: https://registry.hub.docker.com
[2017-12-08T14:53:39.193Z] [DEBUG] Creating filter for registry: dh
[2017-12-08T14:53:39.193Z] [DEBUG] whitelist: [.*-apb$]
[2017-12-08T14:53:39.193Z] [DEBUG] blacklist: []
[2017-12-08T14:53:39.193Z] [DEBUG] Initializing WorkEngine
[2017-12-08T14:53:39.193Z] [DEBUG] Active work engine topics: map[provision_topic:0xc42013d740 deprovision_topic:0xc42013d7a0 update_topic:0xc42013d800]
[2017-12-08T14:53:39.193Z] [DEBUG] Creating AnsibleBroker
[2017-12-08T14:53:39.193Z] [INFO] No cluster credential overrides provided, using k8s InClusterConfig
[2017-12-08T14:53:39.194Z] [DEBUG] Logging into openshift...
[2017-12-08T14:53:39.194Z] [INFO] Listening for provision messages
[2017-12-08T14:53:39.194Z] [INFO] Listening for deprovision messages
[2017-12-08T14:53:39.195Z] [INFO] Listening for provision messages
[2017-12-08T14:53:39.446Z] [DEBUG] Login output:
[2017-12-08T14:53:39.446Z] [DEBUG] Logged into "https://172.30.0.1:443" as "system:serviceaccount:ansible-service-broker:asb" using the token provided.
You have access to the following projects and can switch between them with 'oc project <projectname>':
    ansible-service-broker
  * default
    kube-public
    kube-service-catalog
    kube-system
    myproject
    openshift
    openshift-infra
    openshift-node
    openshift-template-service-broker
Using project "default".
Welcome! See 'oc help' to get started.

[2017-12-08T14:53:39.446Z] [INFO] Initiating Recovery Process
[2017-12-08T14:53:39.446Z] [DEBUG] Dao::FindByState
[2017-12-08T14:53:39.447Z] [INFO] No jobs to recover
[2017-12-08T14:53:39.447Z] [NOTICE] 
[2017-12-08T14:53:39.447Z] [INFO] Broker configured to bootstrap on startup
[2017-12-08T14:53:39.447Z] [INFO] Attempting bootstrap...
[2017-12-08T14:53:39.447Z] [INFO] AnsibleBroker::Bootstrap
[2017-12-08T14:53:39.447Z] [DEBUG] Dao::BatchGetRaw
[2017-12-08T14:53:39.447Z] [DEBUG] DockerHubAdapter::GetImages
[2017-12-08T14:53:39.447Z] [DEBUG] BundleSpecLabel: com.redhat.apb.spec
[2017-12-08T14:53:39.447Z] [DEBUG] Loading image list for org: [ ansibleplaybookbundle ]
[2017-12-08T14:53:42.614Z] [ERROR] unable to generate docker hub token - Post https://hub.docker.com/v2/users/login/: dial tcp 54.156.233.45:443: getsockopt: no route to host
[2017-12-08T14:53:42.615Z] [ERROR] unable to retrieve image names for registry dh - Post https://hub.docker.com/v2/users/login/: dial tcp 54.156.233.45:443: getsockopt: no route to host
[2017-12-08T14:53:42.615Z] [WARNING] registry: 0x1ce8490 was unable to complete bootstrap - Post https://hub.docker.com/v2/users/login/: dial tcp 54.156.233.45:443: getsockopt: no route to host
[2017-12-08T14:53:42.615Z] [ERROR] Failed to bootstrap on startup!
[2017-12-08T14:53:42.615Z] [ERROR] all registries failed on bootstrap
```

I tested agains 3.7.0 as well -with the same results.

I went though https://github.com/openshift/ansible-service-broker#prerequisites 
with Red Hat Enterprise Linux Server release 7.4 (Maipo)
The same errors on Ubuntu 17.4 as well.

**What you expected to happen**:

Just start the ASB successfully :)

**How to reproduce it**:

Follow https://github.com/openshift/ansible-service-broker#deploy-an-openshift-origin-cluster-with-the-ansible-service-broker

**Comment by rthallisey** [comment]
Does this happen consistently?  Doesn't look like docker got the token request.

**Comment by matihost** [comment]
Yes - i believe it is some network issue.
It seems container cannot leave to the internet here. 

I went through https://github.com/openshift/ansible-service-broker#prerequisites networking steps
```
mati@matihost tmp]$ sysctl net.ipv4.ip_forward
net.ipv4.ip_forward = 1
[mati@matihost tmp]$ docker network inspect -f "{{range .IPAM.Config }}{{ .Subnet }}{{end}}" bridge
172.17.0.0/16
# RH 7.4  docker-latest package contains docker 13
[mati@matihost tmp]$ sudo cat /etc/docker-latest/daemon.json
{
 "insecure-registries": [
  "172.30.0.0/16"
 ],
 "log-driver": "journald",
 "signature-verification" : false
}

[mati@matihost tmp]$ firewall-cmd --get-active-zones
dockerc
  sources: 172.17.0.0/16
public
  interfaces: enp0s3
[mati@matihost tmp]$ firewall-cmd --info-zone=dockerc
dockerc (active)
  target: default
  icmp-block-inversion: no
  interfaces: 
  sources: 172.17.0.0/16
  services: 
  ports: 8443/tcp 53/udp 8053/udp 443/tcp 80/tcp
  protocols: 
  masquerade: no
  forward-ports: 
  source-ports: 
  icmp-blocks: 
  rich rules: 
```
and OpenShift  itself works ok

**Comment by rthallisey** [comment]
Could try these iptables rules for docker0:
```bash
sudo iptables -t nat -I POSTROUTING ! -o docker0 -s  172.17.0.0/16 -j MASQUERADE
sudo iptables -I FORWARD -o docker0 -j ACCEPT
sudo iptables -I FORWARD -i docker0 ! -o docker0 -j ACCEPT
```

**Comment by matihost** [comment]
Progress ... however this time the last oc process finishes with error:

```
+ curl -s https://raw.githubusercontent.com/openshift/ansible-service-broker/master/templates/deploy-ansible-service-broker.template.yaml
+ oc create -f -
+ oc process -n ansible-service-broker -p DOCKERHUB_ORG=ansibleplaybookbundle -p ENABLE_BASIC_AUTH=false -p ETCD_TRUSTED_CA_FILE=/var/run/etcd-auth-secret/ca.crt -p BROKER_CLIENT_CERT_PATH=/var/run/asb-etcd-auth/client.crt -p BROKER_CLIENT_KEY_PATH=/var/run/asb-etcd-auth/client.key -p 'ETCD_TRUSTED_CA=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZMekNDQXhlZ0F3SUJBZ0lKQUxCU1FSb0Y3
...
RGJESmJnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==' -p 'BROKER_CLIENT_CERT=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR1ekNDQWFNQ0NRRGxBZ2lhYXV2WENUQU5C
...
Y2lLeStHSGV1aSs1Vms4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==' -p 'BROKER_CLIENT_KEY=LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBbXNyLzd4R090
...
LUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=' -p NAMESPACE=ansible-service-broker -p BROKER_CA_CERT=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM2akNDQWRLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFtTVNRd0lnWURWUVFEREJ0dmNHVnUKYzJocFpuUXRjMmxuYm1WeVFERTFNVEl6TVRBNU5UZ3dIaGNOTVRjeE1qQXpNVFF5TWpNM1doY05Nakl4TWpBeQpNVFF5TWpNNFdqQW1NU1F3SWdZRFZRUUREQnR2Y0dWdWMyaHBablF0YzJsbmJtVnlRREUxTVRJek1UQTVOVGd3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURTRXlOaUFYc25ESmQwL0Fna2xNakEKRWpEaEt0Qi9FN2svY1IzYTFLbkFLNHJIZk12YkFZcGR6TW40djhsMTBYMTdRMnZrOHZmYTU0QTlWSkt2MUdMOQptSXVLcERTWlJyd216ajMxOXRaQnh4aUMyUFpOVUMrZTY3ZmlPOGEyYllFSTBBR3IyVzVQU0FVWlBWYzFVRnhtCmV4SkdCMDBhSFRab1FUS1RFK2RvNUNvd3A0RFlrTlhyaUdRb3VrdkFPdXJxOXI4OG5WdlBQSEl3R1B0eXJOVUsKTjA0QXlOUmRaNW5PNEFuN1dDWUJQOFRRV1hLRVc3dHpWWkNOS0pDeVJrbzR4eVNnT1JLQnlDSHMrdHU0RXVMVQp0TnBpc0hXU1hQSEpVTmNMNmtlMitpVnord2dEOHpaN2ZtMmgyR2xFQTNMRzVMdWNQS1ZKakNpLzQ0T0hHS2JYCkFnTUJBQUdqSXpBaE1BNEdBMVVkRHdFQi93UUVBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUcKU0liM0RRRUJDd1VBQTRJQkFRQWJITGRUUGZnTFNodFpNSEdQRFA5b1FKSjNCZ2pPTWNBWTdDejZybVp4dXgwcgp1ak5NYU1ZMFBVNlhGUjJEM3BmdGM4SHk2TUI2a1lWb1E3Q1h0dTloYUcwWWRwL2xUMU0xTE5WQ3B4VktJeU9MCnVrSkE5eCtDdzVUMEEyZktDNzBNYW1MdXRQY1BxTXl0enR4MGVnVTgzVld5R2daaEk5RUJZM0ZVMHRWZ0RmenUKRGxOQXIrc1BtY1pEUXg3NjZBMVJpemVudWdwTWVNVStzZ21qTE9GS0pUNXIxK09ETDV3SEhzT2tGK2dRNjFtMwo1c29acGhhV3JweDlGeGlFNnNBWUFiY3pMNzJCQ0VmblVaa21LdnlmeVE5WnpoWmYyNGlJRmx0TVBOVTNUT3k1CnJ0VGxyTkN6OTUrVSswZ2svVVh0TVRVLzV6Zm95UnZYZXBZU0lqb2gKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQoKLS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDakNDQWZLZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREEyTVRRd01nWURWUVFEREN0dmNHVnUKYzJocFpuUXRjMlZ5ZG1salpTMXpaWEoyYVc1bkxYTnBaMjVsY2tBeE5URXlNekV3T1RVNU1CNFhEVEUzTVRJdwpNekUwTWpJek9Wb1hEVEl5TVRJd01qRTBNakkwTUZvd05qRTBNRElHQTFVRUF3d3JiM0JsYm5Ob2FXWjBMWE5sCmNuWnBZMlV0YzJWeWRtbHVaeTF6YVdkdVpYSkFNVFV4TWpNeE1EazFPVENDQVNJd0RRWUpLb1pJaHZjTkFRRUIKQlFBRGdnRVBBRENDQVFvQ2dnRUJBUHJtNTkrTHBvVTkrUDBxTE9RejhFRzgrbVBWZmxNS3VaY1pqa0g4TG9rbwpENE1QRHRBOEY4ZFdQZGtGWUVHcTQ0Ulo3ZzR6a1V4L0J4WGFmcEFxTFE3eEFjc0pBQklHdzhVVHNKdzJaZ1RJCk1lWFVYMExTbWduc0lIOUgrUGFLRVJyVlY3ZFZqL0VCZ29ubTArZnNIUGU0WHJQYTVROGh3NDhpQmFQdFV4NysKdDdtN09iODJ3a1plc3hmV1daeDN4Q1E5WUliNUFkanByT0pLc1Bnajhaa3NQQW1ncDFXL0ZZb3Bic1p5ZVdvdQpuTHdZeTZaSlF3YWlkelEycUp2NFZVNE5RckRJSzFabkpBNzFZUHJqTndwdU9LQmxqekk0U01QK2ZnanMrMkV6CjBvd1phbGYxUUFTTjh2SkVGZnpSY1hkS0NtMzFxM3cybWg5dDZMZlVlTk1DQXdFQUFhTWpNQ0V3RGdZRFZSMFAKQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCL3dRRk1BTUJBZjh3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQU02TApUSHhLU0U4M3pIYWh1ckxTS3FHMTJsUFh6cGE2eTl5NG9SRDAwYXBKYXZ0Yy92TWU0bzR0MFNwZWJLOThRMVFsCjRIVVB5UDVEZnYyOVNFNldOTVRONjZYVUh2WDdHZWw5VmhqVERJTVpjcGpBUGhkWTl4bWJ5cnljMEI4VjYvSGQKd3QxZzVRZExqWWxtYkUyTk1nOEdxQzRjU29sbVZ0SjN4Z1RYNkxJWVlPU1FTa0ExSVlhejI5VHRoajFBdjdQTwpTQUcwTTMxZmhaTkk3RHVTQVdZdlJHTjliNnp6QVRNYWhzLzJMMVV2a3ZQaVZ6Q3JXSU1YNTFTVjZwYXpWMGpVClJIUzFPR2VDYXBMNWRCelN4aFJTV1B3NWgxd2h5U3RZOEdSeHBxREJSN1JhN0ZHSnE2YTJKL1pTS0Rwd1MvRzUKdEhiUzBEa2JzL2g2L1J4bDNEQT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo= -f -
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/openshift/origin/pkg/oc/cli/cmd.RunProcess(0xc420052750, 0x71514a0, 0xc42000e010, 0x71514e0, 0xc42000e018, 0x71514e0, 0xc42000e020, 0xc420f72d80, 0xc420fbe780, 0x0, ...)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originspII_P/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/cmd/process.go:242 +0x2233
github.com/openshift/origin/pkg/oc/cli/cmd.NewCmdProcess.func1(0xc420f72d80, 0xc420fbe780, 0x0, 0x18)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originspII_P/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/pkg/oc/cli/cmd/process.go:84 +0x95
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).execute(0xc420f72d80, 0xc420fbe600, 0x18, 0x18, 0xc420f72d80, 0xc420fbe600)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originspII_P/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:603 +0x22b
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc4203d8480, 0xc42000e020, 0xc4203d8480, 0x7)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originspII_P/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:689 +0x339
github.com/openshift/origin/vendor/github.com/spf13/cobra.(*Command).Execute(0xc4203d8480, 0x2, 0xc4203d8480)
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originspII_P/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/vendor/github.com/spf13/cobra/command.go:648 +0x2b
main.main()
	/tmp/openshift/build-rpm-release/tito/rpmbuild-originspII_P/BUILD/origin-3.7.0/_output/local/go/src/github.com/openshift/origin/cmd/oc/oc.go:36 +0x1ae
error: no objects passed to create
+ '[' 1 -ne 0 ']'
+ echo 'Error processing template and creating deployment'
Error processing template and creating deployment
+ exit
```

**Comment by rthallisey** [comment]
@matihost That looks like a syntax issue with the oc process cmd. Did you ever resolve it?

**Comment by rthallisey** [comment]
I haven't been able to reproduce.  Feel free to re open if you're still hitting the issue.

**Comment by ReToCode** [comment]
I had the same issue and was able to find out the root cause. Maybe this helps someone :)

The issue occurs, if you create a cluster with `oc cluster up` and then change the network and it's DNS config. The kubedns will generate a file `openshift.local.clusterup/kubedns/resolv.conf` with the old DNS server in it. Then kubedns will not resolve anything outside of the cluster. Then the automation-broker pod cannot connect to the internet and will not display any APB items in the service broker UI.

To fix this, just change the `resolv.conf` file to a valid DNS server, restart the cluster and you will have the APB in the service broker UI.
