### ISSUE TITLE
Panic on provision when containerStatus.State is nil

### ISSUE THREAD

**Issue by maleck13** [openshift/ansible-service-broker#612]
**This form is for bug reports and feature requests. Major features will go through a [spec process](https://github.com/openshift/ansible-service-broker/blob/master/CONTRIBUTING.md).**
> # Bug:

**What happened**:
During Provision the container state can be nil as it is a pointer. This causes a panic and looks to cause the broker to restart. This is likely due to the panic and there being no recover function.
However when the broker restarts, the Job is in a "in progress" state and a recovery is attempted.
This seems as though it can cause a crash loop as the Job keeps failing and the broker keeps attempting to recover it as the Job remains "in progress". 

This particular issue is relatively simple to fix by adding a nil check which I will add in a subsequent PR, however I think it raises a bigger question around how the broker should recover from this kind of situation.

Is it intention for the broker to exit on panic and restart? (It's worth noting that until the broker restarts no services will be able to be provisioned etc for potentially several minutes (not sure what the service catalog does if it cannot reach the broker probably goes into a retry backoff state)).

If we don't want it to crash we should probably add a recover function that can mark the job as failed on panic or somehow limit the number of attempts to recover the Job.
If the broker should exit on panic and restart then it seems there remains the risk of a panic happening and a state being created in which the it keeps panicking and the broker does not restart properly until the data is changed in etcd.

**How to reproduce it**:
Not sure there is a reliable way, for me it was because a pod ContainerStatus.State was nil and seemed to remain nil during each recover.

**Log**
```

[2018-01-04T19:11:10.995Z] [INFO] - == REGISTRY CX ==
--
  | [2018-01-04T19:11:10.996Z] [INFO] - Name: localregistry
  | [2018-01-04T19:11:10.996Z] [INFO] - Type: local_openshift
  | [2018-01-04T19:11:10.996Z] [INFO] - Url:
  | [2018-01-04T19:11:10.996Z] [DEBUG] - Creating filter for registry: localregistry
  | [2018-01-04T19:11:10.997Z] [DEBUG] - whitelist: [.*-apb$]
  | [2018-01-04T19:11:10.997Z] [DEBUG] - blacklist: []
  | [2018-01-04T19:11:10.997Z] [DEBUG] - Initializing WorkEngine
  | [2018-01-04T19:11:10.997Z] [INFO] - Listening for deprovision messages
  | [2018-01-04T19:11:10.997Z] [INFO] - Listening for update messages
  | [2018-01-04T19:11:10.997Z] [INFO] - Listening for provision messages
  | [2018-01-04T19:11:10.997Z] [DEBUG] - Active work engine topics: map[provision_topic:0xc420053d40 deprovision_topic:0xc420053da0 update_topic:0xc420053e00]
  | [2018-01-04T19:11:10.998Z] [DEBUG] - Unable to get secrets from config
  | [2018-01-04T19:11:10.998Z] [DEBUG] - Creating AnsibleBroker
  | [2018-01-04T19:11:10.998Z] [DEBUG] - Unable to get namespace from config
  | [2018-01-04T19:11:10.998Z] [DEBUG] - Unable to get cluster_url from config
  | [2018-01-04T19:11:10.998Z] [INFO] - Initiating Recovery Process
  | [2018-01-04T19:11:10.998Z] [DEBUG] - Dao::FindByState
  | [2018-01-04T19:11:10.999Z] [DEBUG] - Successfully loaded [ 2 ] jobstate objects from etcd dir [ /state/ ]
  | [2018-01-04T19:11:11.011Z] [DEBUG] - Skipping, jobstate [{3195b2ae-37c1-4318-85c5-d5198f3d7aac succeeded apb-c3a7f13a-00d8-4b2c-9001-b4a6e529d2c3 provision }] did not match given state: [in progress].
  | [2018-01-04T19:11:11.011Z] [DEBUG] - Skipping, jobstate [{d85d2197-f76e-4159-a262-2ae677c33b9b succeeded  deprovision }] did not match given state: [in progress].
  | [2018-01-04T19:11:11.012Z] [DEBUG] - Found! jobstate [{843706f0-1372-46e1-abe4-2652f85cc770 in progress  provision }] matched given state: [in progress].
  | [2018-01-04T19:11:11.013Z] [INFO] - No podname. Attempting to restart job: c6dce144-4712-4242-a4a7-5356ac324ec8
  | [2018-01-04T19:11:11.013Z] [DEBUG] - &{c6dce144-4712-4242-a4a7-5356ac324ec8 0xc4206820b0 0xc420086620 0xc42000c040 map[]}
  | [2018-01-04T19:11:11.013Z] [NOTICE] - ============================================================
  | [2018-01-04T19:11:11.013Z] [NOTICE] -                        PROVISIONING
  | [2018-01-04T19:11:11.013Z] [NOTICE] - ============================================================
  | [2018-01-04T19:11:11.013Z] [NOTICE] - Spec.ID: b43a4272a6efcaaa3e0b9616324f1099
  | [2018-01-04T19:11:11.013Z] [NOTICE] - Spec.Name: dh-hello-world-db-apb
  | [2018-01-04T19:11:11.013Z] [NOTICE] - Spec.Image: docker.io/ansibleplaybookbundle/hello-world-db-apb:latest
  | [2018-01-04T19:11:11.013Z] [NOTICE] - Spec.Description: A sample APB which deploys Hello World Database
  | [2018-01-04T19:11:11.013Z] [NOTICE] - ============================================================
  | [2018-01-04T19:11:11.013Z] [INFO] - Checking if namespace testdb exists.
  | [2018-01-04T19:11:11.014Z] [INFO] - Recovery complete
  | [2018-01-04T19:11:11.014Z] [NOTICE] - recover called
  | [2018-01-04T19:11:11.014Z] [INFO] - Broker configured to bootstrap on startup
  | [2018-01-04T19:11:11.014Z] [INFO] - Attempting bootstrap...
  | [2018-01-04T19:11:11.015Z] [INFO] - AnsibleBroker::Bootstrap
  | [2018-01-04T19:11:11.015Z] [DEBUG] - Dao::BatchGetRaw
  | [2018-01-04T19:11:11.015Z] [DEBUG] - Successfully loaded [ 0 ] objects from etcd dir [ /spec ]
  | [2018-01-04T19:11:11.015Z] [DEBUG] - DockerHubAdapter::GetImages
  | [2018-01-04T19:11:11.015Z] [DEBUG] - BundleSpecLabel: com.redhat.apb.spec
  | [2018-01-04T19:11:11.015Z] [DEBUG] - Loading image list for org: [ ansibleplaybookbundle ]
  | [2018-01-04T19:11:11.047Z] [DEBUG] - ExecutingApb:
  | [2018-01-04T19:11:11.047Z] [DEBUG] - name:[ dh-hello-world-db-apb ]
  | [2018-01-04T19:11:11.048Z] [DEBUG] - image:[ docker.io/ansibleplaybookbundle/hello-world-db-apb:latest ]
  | [2018-01-04T19:11:11.048Z] [DEBUG] - action:[ provision ]
  | [2018-01-04T19:11:11.048Z] [DEBUG] - pullPolciy:[ IfNotPresent ]
  | [2018-01-04T19:11:11.048Z] [DEBUG] - role:[ edit ]
  | [2018-01-04T19:11:11.076Z] [DEBUG] - Trying to create apb sandbox: [ apb-ed415153-d376-40ae-9d7d-f9a7978ddf50 ], with edit permissions in namespace dh-hello-world-db-apb-prov-wplkz
  | [2018-01-04T19:11:11.076Z] [NOTICE] - Creating RoleBinding apb-ed415153-d376-40ae-9d7d-f9a7978ddf50
  | [2018-01-04T19:11:11.252Z] [NOTICE] - Creating RoleBinding apb-ed415153-d376-40ae-9d7d-f9a7978ddf50
  | [2018-01-04T19:11:11.279Z] [INFO] - Successfully created apb sandbox: [ apb-ed415153-d376-40ae-9d7d-f9a7978ddf50 ], with edit permissions in namespace dh-hello-world-db-apb-prov-wplkz
  | [2018-01-04T19:11:11.279Z] [NOTICE] - Creating pod "apb-ed415153-d376-40ae-9d7d-f9a7978ddf50" in the dh-hello-world-db-apb-prov-wplkz namespace
  | [2018-01-04T19:11:11.331Z] [DEBUG] - Watching pod [ apb-ed415153-d376-40ae-9d7d-f9a7978ddf50 ] in namespace [ dh-hello-world-db-apb-prov-wplkz ] for completion
  | [2018-01-04T19:11:11.331Z] [INFO] - Watch pod [ apb-ed415153-d376-40ae-9d7d-f9a7978ddf50 ] tick 1
  | [2018-01-04T19:11:11.337Z] [DEBUG] - Pod [ apb-ed415153-d376-40ae-9d7d-f9a7978ddf50 ] Pending
  | [2018-01-04T19:11:13.579Z] [DEBUG] - Trying to load ansibleplaybookbundle/s2i-apb
  | [2018-01-04T19:11:13.579Z] [DEBUG] - Trying to load ansibleplaybookbundle/hello-world-apb
  | [2018-01-04T19:11:13.579Z] [DEBUG] - Trying to load ansibleplaybookbundle/pyzip-demo-apb
  | [2018-01-04T19:11:13.579Z] [DEBUG] - Trying to load ansibleplaybookbundle/hello-world-db-apb
  | [2018-01-04T19:11:13.579Z] [DEBUG] - Trying to load ansibleplaybookbundle/jenkins-apb
  | [2018-01-04T19:11:13.579Z] [DEBUG] - Trying to load ansibleplaybookbundle/rocketchat-apb
  | [2018-01-04T19:11:13.579Z] [DEBUG] - Trying to load ansibleplaybookbundle/hastebin-apb
  | [2018-01-04T19:11:13.579Z] [DEBUG] - Trying to load ansibleplaybookbundle/wordpress-ha-apb
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/etherpad-apb
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/rds-postgres-apb
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/pyzip-demo-db-apb
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/thelounge-apb
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/manageiq-apb
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/nginx-apb
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/postgresql-apb
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/mediawiki-apb
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/mysql-apb
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/mariadb-apb
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/origin-ansible-service-broker
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/ansible-service-broker
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/mediawiki123
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/apb-base
  | [2018-01-04T19:11:13.58Z] [DEBUG] - Trying to load ansibleplaybookbundle/hello-world
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/origin-service-catalog
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/rhscl-postgresql-apb
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/rhscl-mysql-apb
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/mediawiki123-apb
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/rhscl-mariadb-apb
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/py-zip-demo
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/apb-tools
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/apb-assets-base
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/asb-installer
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/deploy-broker
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/origin
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/origin-deployer
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/origin-docker-registry
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/origin-haproxy-router
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/origin-pod
  | [2018-01-04T19:11:13.581Z] [DEBUG] - Trying to load ansibleplaybookbundle/origin-sti-builder
  | [2018-01-04T19:11:13.582Z] [DEBUG] - Trying to load ansibleplaybookbundle/origin-recycler
  | [2018-01-04T19:11:13.582Z] [DEBUG] - Filter applied against registry: dh
  | [2018-01-04T19:11:13.582Z] [DEBUG] - APBs passing white/blacklist filter:
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/hello-world-db-apb
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/postgresql-apb
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/mariadb-apb
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/rhscl-postgresql-apb
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/s2i-apb
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/pyzip-demo-apb
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/pyzip-demo-db-apb
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/thelounge-apb
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/hello-world-apb
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/rocketchat-apb
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/etherpad-apb
  | [2018-01-04T19:11:13.582Z] [DEBUG] - -> ansibleplaybookbundle/rds-postgres-apb
  | [2018-01-04T19:11:13.583Z] [DEBUG] - -> ansibleplaybookbundle/nginx-apb
  | [2018-01-04T19:11:13.583Z] [DEBUG] - -> ansibleplaybookbundle/mysql-apb
  | [2018-01-04T19:11:13.583Z] [DEBUG] - -> ansibleplaybookbundle/rhscl-mysql-apb
  | [2018-01-04T19:11:13.583Z] [DEBUG] - -> ansibleplaybookbundle/rhscl-mariadb-apb
  | [2018-01-04T19:11:13.583Z] [DEBUG] - -> ansibleplaybookbundle/jenkins-apb
  | [2018-01-04T19:11:13.583Z] [DEBUG] - -> ansibleplaybookbundle/mediawiki123-apb
  | [2018-01-04T19:11:13.583Z] [DEBUG] - -> ansibleplaybookbundle/wordpress-ha-apb
  | [2018-01-04T19:11:13.583Z] [DEBUG] - -> ansibleplaybookbundle/manageiq-apb
  | [2018-01-04T19:11:13.583Z] [DEBUG] - -> ansibleplaybookbundle/mediawiki-apb
  | [2018-01-04T19:11:13.583Z] [DEBUG] - -> ansibleplaybookbundle/hastebin-apb
  | [2018-01-04T19:11:15.156Z] [DEBUG] - Registry::imageToSpec
  | [2018-01-04T19:11:16.338Z] [INFO] - Watch pod [ apb-ed415153-d376-40ae-9d7d-f9a7978ddf50 ] tick 2
  | [2018-01-04T19:11:16.343Z] [INFO] - Destroying APB sandbox...
  | [2018-01-04T19:11:16.345Z] [DEBUG] - Keeping namespace alive due to configuration
  | [2018-01-04T19:11:16.345Z] [DEBUG] - Deleting rolebinding apb-ed415153-d376-40ae-9d7d-f9a7978ddf50, namespace dh-hello-world-db-apb-prov-wplkz
  | [2018-01-04T19:11:16.35Z] [NOTICE] - Successfully deleted rolebinding apb-ed415153-d376-40ae-9d7d-f9a7978ddf50, namespace dh-hello-world-db-apb-prov-wplkz
  | [2018-01-04T19:11:16.35Z] [DEBUG] - Deleting rolebinding apb-ed415153-d376-40ae-9d7d-f9a7978ddf50, namespace testdb
  | [2018-01-04T19:11:16.354Z] [NOTICE] - Successfully deleted rolebinding apb-ed415153-d376-40ae-9d7d-f9a7978ddf50, namespace testdb
  | panic: runtime error: invalid memory address or nil pointer dereference
  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1495c69]
  |  
  | goroutine 32 [running]:
  | github.com/openshift/ansible-service-broker/pkg/apb.errorPullingImage(0xc4205fe3c0, 0x1, 0x4, 0x28)
  | /Users/kelly/projects/src/github.com/openshift/ansible-service-broker/pkg/apb/watch_pod.go:83 +0x39
  | github.com/openshift/ansible-service-broker/pkg/apb.watchPod(0xc420347c50, 0x28, 0xc4201e2880, 0x20, 0xc420347c50, 0x28)
  | /Users/kelly/projects/src/github.com/openshift/ansible-service-broker/pkg/apb/watch_pod.go:55 +0x64a
  | github.com/openshift/ansible-service-broker/pkg/apb.provisionOrUpdate(0x18f5ae8, 0x9, 0xc42025a240, 0x0, 0x0, 0x0, 0x0, 0x0)
  | /Users/kelly/projects/src/github.com/openshift/ansible-service-broker/pkg/apb/provision_or_update.go:82 +0x714
  | github.com/openshift/ansible-service-broker/pkg/apb.Provision(0xc42025a240, 0x10, 0x10, 0xc4203478c0, 0x24, 0x42ad68)
  | /Users/kelly/projects/src/github.com/openshift/ansible-service-broker/pkg/apb/provision.go:36 +0x3c8
  | github.com/openshift/ansible-service-broker/pkg/broker.(*ProvisionJob).Run(0xc42042e4d0, 0xc4200a0ff0, 0x24, 0xc420053d40)
  | /Users/kelly/projects/src/github.com/openshift/ansible-service-broker/pkg/broker/provision_job.go:56 +0x152
  | created by github.com/openshift/ansible-service-broker/pkg/broker.(*WorkEngine).StartNewJob
  | /Users/kelly/projects/src/github.com/openshift/ansible-service-broker/pkg/broker/work_engine.go:64 +0x10b

```

**Comment by rthallisey** [comment]
It could be that the container gets deleted then watchPod checks the status of the container and gets nil.

**Comment by maleck13** [comment]
@rthallisey While my PR solved the specific problem, do you think there is value is raising an issue around how the broker deals with panics in general?
In this particular case the broker failed to ever come back up again as each time it tried to recover the Job it would panic and crash again.

**Comment by rthallisey** [comment]
@maleck13 I think it is worth raising an issue. The only recovery we do now is for recovering apbs and not the broker.  When the broker panics, we may need to a roll back/reset/remove the last operation to allow for a safe restart. To use a buzz word, the broker needs to be more cloud native.

**Comment by maleck13** [comment]
follow up created
